### ISSUE TITLE
 addon for locust

### ISSUE THREAD

**Issue by yogeshVU** [zlorb/locust.replay#1]
Since the locust.replay is no more an integral part of mitmproxy, is there any plans to integrate this as an addon for the mitmproxy?

**Comment by zlorb** [comment]
mitmproxy already has the feature to extract specific flows as locust code and as a locust task.
locust.replay is more of a sample script to extract multiple flows with multiple destinations to a set of usable locust scripts. Any thoughts on how this would fit into mitmproxy work-flow in a non-script way are welcome.

**Comment by yogeshVU** [comment]
looks like it was recently removed from the mitmproxy. 
https://github.com/mitmproxy/mitmproxy/commit/bcbe87bb0986819c83c3e2efc683194bbf9c6c50

**Comment by zlorb** [comment]
Thanks for pointing this out. Looks like both requests and locust export have been kicked out of mitmproxy. It will take me a while until I have time to look into this again. Any help is welcomed.
The locust_extractor script should continue working for now (didn't test with latest mitmproxy).

**Comment by zlorb** [comment]
Resolved for mitmproxy v3 and v4. Tested with v4.0.1 only.
