### ISSUE TITLE
Locust "EOL while scanning string literal"

### ISSUE THREAD

**Issue by ZukkyBaig** [zlorb/locust.replay#10]
Hi,

I managed to run the locust script in mitmproxy using linux subsystem in Windows perfectly. I used: locust.code.clip "~d hosturl.com" and it brought back the locust script. However, the 'data' variable in the Locustfile is like this:

`data = '''b'{"pageName":"getStarted","initialPageLoad":5050,"finishedLoadTime":2120}''''`

When I run the locustfile.py, an error is outputted:

`Syntax Error: EOL while scanning string literal` 

Which then points to the abovementioned code line. I have tried different variations to get this to read correctly, if you have faced this issue before, what would you suggest to use?

**Comment by zlorb** [comment]
Can you please share python, mitmproxy, and locust versions, as well as the command line used to run the locus file?

**Comment by zlorb** [comment]
Issue should be fixed now.
