### ISSUE TITLE
Using on windows

### ISSUE THREAD

**Issue by nikita1412** [zlorb/locust.replay#4]
According to this repo's readme , the shortcuts(E & I) are required to generate the load test script of locust , but the interactive mitmproxy console is not supported on windows. Is there any work around to generate the same locust script on windows?

**Comment by zlorb** [comment]
The functionality to export locust option was removed from recent mitmproxy versions. 
Some point in the future I may have time to convert this code to an external add-on.
In the meanwhile, you can continue using the locust_extractor script (mitmdump -s ...).
